// Generated by CoffeeScript 1.12.4
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  router.get('/', function(req, res, next) {
    return res.render('layout', {
      title: 'ТОП 10'
    });
  });

  module.exports = router;

}).call(this);
