// Generated by CoffeeScript 1.11.1
(function() {
  var express, fs, getTop10FromFS, path, polling, router, utils;

  express = require('express');

  router = express.Router();

  utils = require('../utils/utils');

  path = require('path');

  fs = require('fs');

  polling = require('../utils/polling');

  getTop10FromFS = function(date) {
    var cont, dest;
    try {
      dest = path.join(global.app_root, global.app_config.data_dir, "top10/" + date + ".json");
      return cont = JSON.parse(fs.readFileSync(dest, 'utf8'));
    } catch (error) {
      throw new SyntaxError("TOP10 does not exist for " + date + " !!!");
    }
  };

  router.get('/', function(req, res, next) {
    var date, e;
    date = utils.getNowDate();
    try {
      return res.send(getTop10FromFS(date));
    } catch (error) {
      try {
        date = utils.getNowDate(1);
        return res.send(getTop10FromFS(date));
      } catch (error) {
        e = error;
        polling.get_top_from_remote(function() {});
        return res.send({
          status: 1,
          message: e.message
        });
      }
    }
  });

  module.exports = router;

}).call(this);
