// Generated by CoffeeScript 1.11.1
(function() {
  var express, fs, getTop10FromFS, path, polling, router, utils;

  express = require('express');

  router = express.Router();

  utils = require('../utils/utils');

  path = require('path');

  fs = require('fs');

  polling = require('../utils/polling');

  getTop10FromFS = function(offset) {
    var cont, date, dest;
    if (offset == null) {
      offset = 0;
    }
    date = utils.getNowDate(offset);
    try {
      dest = path.join(global.app_root, global.app_config.data_dir, "top10/" + date + ".json");
      return cont = JSON.parse(fs.readFileSync(dest, 'utf8'));
    } catch (error) {
      offset = offset + 1;
      return getTop10FromFS(offset);
    }
  };

  router.get('/', function(req, res, next) {
    var e;
    try {
      return res.send(getTop10FromFS(date));
    } catch (error) {
      try {
        return res.send(getTop10FromFS());
      } catch (error) {
        e = error;
        polling.get_top_from_remote(function() {});
        return res.send({
          status: 1,
          message: e.message
        });
      }
    }
  });

  module.exports = router;

}).call(this);
