// Generated by CoffeeScript 1.11.1
(function() {
  var express, fs, path, polling, router, utils;

  express = require('express');

  router = express.Router();

  utils = require('../utils/utils');

  path = require('path');

  fs = require('fs');

  polling = require('../utils/polling');

  router.get('/', function(req, res, next) {
    var cont, dest, num;
    dest = path.join(global.app_root, global.app_config.data_dir, "top10/" + (utils.getNowDate()) + ".json");
    try {
      num = fs.statSync(dest);
      cont = JSON.parse(fs.readFileSync(dest, 'utf8'));
      return res.send(cont);
    } catch (error) {
      polling.grabtop(function() {});
      return res.send(dest + " does not exist");
    }
  });

  module.exports = router;

}).call(this);
