// Generated by CoffeeScript 1.11.1
(function() {
  var data_dir, exec, fs, path, top10_dir, top10_image_dir;

  exec = require('child_process').exec;

  fs = require('fs');

  path = require('path');

  fs.lstat(global.app_root + '/public/node_modules', function(err, stats) {
    var cmd;
    if (err) {
      cmd = "ln -s " + global.app_root + "/node_modules public/node_modules";
      return exec(cmd, function(err, stdout, stdin) {
        console.log(stdout);
        return console.log('Create simlink on node_modules.....');
      });
    }
  });

  data_dir = path.join(global.app_root, global.app_config.data_dir);

  top10_dir = path.join(data_dir, 'top10');

  top10_image_dir = path.join(data_dir, 'top10', 'images');

  if (!fs.existsSync(data_dir)) {
    console.log('Creating data dir......');
    fs.mkdirSync(data_dir);
  }

  if (!fs.existsSync(top10_dir)) {
    console.log('Creating top10_dir ......');
    fs.mkdirSync(top10_dir);
  }

  if (!fs.existsSync(top10_image_dir)) {
    console.log('Creating top10_image_dir ......');
    fs.mkdirSync(top10_image_dir);
  }

}).call(this);
