// Generated by CoffeeScript 1.12.4
(function() {
  var article, article_polling, catalog, catalog_polling, issue, issue_polling, polling, top10, top_polling;

  polling = require('async-polling');

  catalog = require('./polling_catalog');

  issue = require('./polling_issues');

  top10 = require('./polling_top10');

  article = require('./polling_articles');

  issue_polling = polling(issue.process_issues, 60000 * 30);

  issue_polling.run();

  top_polling = polling(top10.get_top10_from_server, 60000 * 30);

  top_polling.run();

  catalog_polling = polling(catalog.get_catalog_from_server, 60000 * 30);

  catalog_polling.run();

  article_polling = polling(article.get_articles_from_server, 60000 * 30);

  article_polling.run();

}).call(this);
