// Generated by CoffeeScript 1.11.1
(function() {
  var debug, fs, http, path, polling, request, utils;

  polling = require('async-polling');

  http = require('http');

  fs = require('fs');

  path = require('path');

  utils = require('../utils/utils');

  request = require('request');

  debug = require('debug')('app-pooling-catalog');

  debug('Poling catalog');

}).call(this);

//# sourceMappingURL=polling_catalog.js.map
