// Generated by CoffeeScript 1.11.1
(function() {
  module.exports = {
    getNowDate: function(diff) {
      var dd, mm, today;
      if (diff == null) {
        diff = 0;
      }
      today = new Date();
      if (diff > 0) {
        today.setDate(today.getDate() - diff);
      }
      console.log(today);
      dd = today.getDate();
      if (dd < 10) {
        dd = '0' + dd;
      }
      mm = today.getMonth() + 1;
      if (mm < 10) {
        mm = '0' + mm;
      }
      return (today.getFullYear()) + "-" + mm + "-" + dd;
    }
  };

}).call(this);
